/**
 * vite-plugin-fullstack
 *
 * A master Vite plugin that wires together the full application stack:
 *   • Express  — dev-mode middleware mode + route registration helpers
 *   • tRPC     — type-safe API layer (superjson transformer, adapter)
 *   • Wouter   — client-side routing with type-safe route map
 *   • Supabase — Realtime / Auth client via @supabase/supabase-js
 *   • Drizzle  — ORM connection pool config + migration guard in dev
 *
 * Virtual modules exposed to the client:
 *   import { trpc }      from "virtual:trpc"
 *   import { supabase }  from "virtual:supabase"
 *   import { ROUTES }    from "virtual:router"
 *
 * Usage in vite.config.ts:
 *   import { fullstackPlugin } from "./plugins/vite-plugin-fullstack"
 *   export default defineConfig({ plugins: [fullstackPlugin(options)] })
 */

import type { Express, RequestHandler } from "express";
import type { Server } from "http";
import path from "node:path";
import type { Plugin, ViteDevServer } from "vite";

// ─── Public API types ──────────────────────────────────────────────────────────

export interface TrpcPluginOptions {
  /** Path where the Express adapter mounts the tRPC router. Default: "/api/trpc" */
  endpoint?: string;
  /**
   * Factory that returns { router, createContext } when called.
   * Loaded lazily so the server bundle stays out of Vite's transform pipeline.
   */
  routerFactory?: () => Promise<{
    router: unknown;
    createContext: (opts: unknown) => Promise<unknown>;
  }>;
}

export interface SupabasePluginOptions {
  /**
   * Log a warning (not an error) when VITE_SUPABASE_URL / KEY are absent.
   * Useful for local dev without Supabase. Default: true
   */
  warnOnMissingEnv?: boolean;
  /**
   * Additional Supabase client options forwarded verbatim. Merged with the
   * plugin's opinionated defaults.
   */
  clientOptions?: Record<string, unknown>;
}

export interface DrizzlePluginOptions {
  /**
   * When true the plugin verifies that DATABASE_URL is set and prints a
   * friendly error instead of crashing at runtime. Default: true
   */
  validateConnectionString?: boolean;
  /**
   * Path to the drizzle config file, used to run `drizzle-kit check` in dev.
   * Set to false to disable. Default: "drizzle.config.ts"
   */
  configFile?: string | false;
}

/** Typed route map for Wouter. Add every app route here. */
export interface RouteMap {
  [key: string]: string;
}

export interface WouterPluginOptions {
  /**
   * Declarative route map injected as `virtual:router`.
   * Keys are logical names, values are the path patterns accepted by Wouter.
   *
   * Example:
   *   routes: {
   *     home:    "/",
   *     login:   "/login",
   *     letter:  "/letter/:id",
   *   }
   */
  routes?: RouteMap;
  /**
   * Route that unauthenticated visitors are redirected to.
   * Injected as ROUTES.LOGIN in the virtual module. Default: "/login"
   */
  loginPath?: string;
}

export interface FullstackPluginOptions {
  trpc?: TrpcPluginOptions;
  supabase?: SupabasePluginOptions;
  drizzle?: DrizzlePluginOptions;
  wouter?: WouterPluginOptions;
  /**
   * Express setup hook — called once after the Express app is created in dev
   * mode. Use it to register additional middlewares or routes that should run
   * BEFORE tRPC.
   */
  configureExpress?: (app: Express) => void | Promise<void>;
}

// ─── Virtual module IDs ────────────────────────────────────────────────────────

const VIRTUAL_TRPC = "virtual:trpc";
const VIRTUAL_SUPABASE = "virtual:supabase";
const VIRTUAL_ROUTER = "virtual:router";

const RESOLVED_TRPC = `\0${VIRTUAL_TRPC}`;
const RESOLVED_SUPABASE = `\0${VIRTUAL_SUPABASE}`;
const RESOLVED_ROUTER = `\0${VIRTUAL_ROUTER}`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function trpcVirtualModule(endpoint: string): string {
  return /* ts */ `
// virtual:trpc — auto-generated by vite-plugin-fullstack
// Re-exports the project's tRPC React client pre-configured with:
//   • httpBatchLink pointing to ${endpoint}
//   • superjson transformer
//   • credentials: "include" (session cookies)

import { createTRPCReact } from "@trpc/react-query";
import { httpBatchLink } from "@trpc/client";
import superjson from "superjson";
import type { AppRouter } from "../server/routers";

export const trpc = createTRPCReact<AppRouter>();

export function buildTrpcClient() {
  return trpc.createClient({
    links: [
      httpBatchLink({
        url: "${endpoint}",
        transformer: superjson,
        fetch(url, options) {
          return fetch(url, { ...options, credentials: "include" });
        },
      }),
    ],
  });
}

export type { AppRouter };
`;
}

function supabaseVirtualModule(opts: SupabasePluginOptions): string {
  return /* ts */ `
// virtual:supabase — auto-generated by vite-plugin-fullstack
// Exports a lazy singleton Supabase client.
// Auth is handled via JWT/session cookies (not Supabase Auth).

import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient, RealtimeChannel } from "@supabase/supabase-js";

const url  = import.meta.env.VITE_SUPABASE_URL  as string | undefined;
const key  = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY
) as string | undefined;

let _client: SupabaseClient | null = null;

/** Returns the Supabase client or null when env vars are missing. */
export function getSupabaseClient(): SupabaseClient | null {
  if (!url || !key) {
    ${opts.warnOnMissingEnv !== false ? 'console.warn("[virtual:supabase] VITE_SUPABASE_URL / KEY not set — Supabase disabled");' : ""}
    return null;
  }
  if (!_client) {
    _client = createClient(url, key, {
      realtime: { params: { eventsPerSecond: 10 } },
      auth: {
        autoRefreshToken: false,
        persistSession: false,
        detectSessionInUrl: false,
      },
    });
  }
  return _client;
}

// ─── Channel registry (avoids duplicate subscriptions) ───────────────────────
const _channels = new Map<string, RealtimeChannel>();

export function getOrCreateChannel(
  key: string,
  factory: (client: SupabaseClient) => RealtimeChannel,
): RealtimeChannel | null {
  const client = getSupabaseClient();
  if (!client) return null;
  if (_channels.has(key)) return _channels.get(key)!;
  const ch = factory(client);
  _channels.set(key, ch);
  return ch;
}

export function removeChannel(key: string): void {
  const client = getSupabaseClient();
  const ch = _channels.get(key);
  if (client && ch) {
    client.removeChannel(ch);
    _channels.delete(key);
  }
}
`;
}

function routerVirtualModule(
  routes: RouteMap,
  loginPath: string,
): string {
  const entries = Object.entries(routes)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join("\n");

  return /* ts */ `
// virtual:router — auto-generated by vite-plugin-fullstack
// Type-safe Wouter route map. Import ROUTES instead of hard-coding paths.

export const ROUTES = {
${entries}
} as const;

export type RouteName = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteName];

/** Convenience: resolve a named route, interpolating :params. */
export function route(
  name: RouteName,
  params?: Record<string, string | number>,
): string {
  let path: string = ROUTES[name];
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      path = path.replace(\`:\${k}\`, String(v));
    }
  }
  return path;
}

/** The path unauthenticated users are sent to. */
export const LOGIN_PATH = ${JSON.stringify(loginPath)};
`;
}

// ─── Health-check middleware (dev only) ───────────────────────────────────────

function healthCheckHandler(): RequestHandler {
  return (_req, res) => {
    res.json({
      ok: true,
      ts: new Date().toISOString(),
      stack: ["express", "trpc", "wouter", "supabase", "drizzle"],
    });
  };
}

// ─── tRPC dev-server middleware ────────────────────────────────────────────────

async function mountTrpcMiddleware(
  app: Express,
  endpoint: string,
  routerFactory: NonNullable<TrpcPluginOptions["routerFactory"]>,
): Promise<void> {
  const { createExpressMiddleware } = await import(
    "@trpc/server/adapters/express"
  );
  const { router, createContext } = await routerFactory();
  app.use(
    endpoint,
    createExpressMiddleware({
      router: router as Parameters<typeof createExpressMiddleware>[0]["router"],
      createContext: createContext as Parameters<
        typeof createExpressMiddleware
      >[0]["createContext"],
    }),
  );
}

// ─── Drizzle env guard ────────────────────────────────────────────────────────

function validateDrizzleEnv(configFile: string | false): void {
  if (!process.env.DATABASE_URL) {
    console.warn(
      "[vite-plugin-fullstack] ⚠  DATABASE_URL is not set — " +
        "Drizzle ORM will fail at runtime.",
    );
  }
  if (configFile) {
    const abs = path.resolve(process.cwd(), configFile);
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      require("fs").accessSync(abs);
    } catch {
      console.warn(
        `[vite-plugin-fullstack] ⚠  Drizzle config not found at ${abs}`,
      );
    }
  }
}

// ─── Plugin factory ───────────────────────────────────────────────────────────

/**
 * fullstackPlugin — the single entry-point.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { fullstackPlugin } from "./plugins/vite-plugin-fullstack";
 *
 * export default defineConfig({
 *   plugins: [
 *     fullstackPlugin({
 *       trpc: { endpoint: "/api/trpc" },
 *       wouter: {
 *         routes: {
 *           home:    "/",
 *           login:   "/login",
 *           letter:  "/letter/:id",
 *           admin:   "/admin",
 *         },
 *       },
 *     }),
 *   ],
 * });
 * ```
 */
export function fullstackPlugin(opts: FullstackPluginOptions = {}): Plugin {
  const trpcOpts: Required<TrpcPluginOptions> = {
    endpoint: opts.trpc?.endpoint ?? "/api/trpc",
    routerFactory: opts.trpc?.routerFactory ?? (() => Promise.resolve({ router: {}, createContext: async () => ({}) })),
  };

  const supabaseOpts: SupabasePluginOptions = {
    warnOnMissingEnv: opts.supabase?.warnOnMissingEnv ?? true,
    clientOptions: opts.supabase?.clientOptions ?? {},
  };

  const drizzleOpts: Required<DrizzlePluginOptions> = {
    validateConnectionString: opts.drizzle?.validateConnectionString ?? true,
    configFile: opts.drizzle?.configFile ?? "drizzle.config.ts",
  };

  const wouterOpts: Required<WouterPluginOptions> = {
    routes: opts.wouter?.routes ?? {},
    loginPath: opts.wouter?.loginPath ?? "/login",
  };

  let _vite: ViteDevServer | undefined;

  return {
    name: "vite-plugin-fullstack",
    enforce: "pre",

    // ── Build-time env validation ────────────────────────────────────────────
    buildStart() {
      if (drizzleOpts.validateConnectionString) {
        validateDrizzleEnv(drizzleOpts.configFile);
      }
    },

    // ── Virtual module resolution ────────────────────────────────────────────
    resolveId(id) {
      if (id === VIRTUAL_TRPC) return RESOLVED_TRPC;
      if (id === VIRTUAL_SUPABASE) return RESOLVED_SUPABASE;
      if (id === VIRTUAL_ROUTER) return RESOLVED_ROUTER;
    },

    load(id) {
      if (id === RESOLVED_TRPC) return trpcVirtualModule(trpcOpts.endpoint);
      if (id === RESOLVED_SUPABASE) return supabaseVirtualModule(supabaseOpts);
      if (id === RESOLVED_ROUTER)
        return routerVirtualModule(wouterOpts.routes, wouterOpts.loginPath);
    },

    // ── Dev server: wire Express into Vite's middleware stack ────────────────
    async configureServer(server: ViteDevServer) {
      _vite = server;

      // Dynamically import Express to keep it out of the client bundle
      const { default: express } = await import("express");
      const app: Express = express();

      // Body parsers
      app.use(express.json({ limit: "50mb" }));
      app.use(express.urlencoded({ limit: "50mb", extended: true }));

      // Health check
      app.get("/__fullstack__/health", healthCheckHandler());

      // User-defined Express config (auth middleware, extra routes, etc.)
      if (opts.configureExpress) {
        await opts.configureExpress(app);
      }

      // tRPC adapter
      if (opts.trpc?.routerFactory) {
        await mountTrpcMiddleware(app, trpcOpts.endpoint, trpcOpts.routerFactory);
      }

      // Attach to Vite's connect middleware stack BEFORE Vite's own handlers
      server.middlewares.use(app);

      console.log(
        `[vite-plugin-fullstack] Express + tRPC mounted (${trpcOpts.endpoint})`,
      );
    },

    // ── Hot-reload for route map changes ────────────────────────────────────
    handleHotUpdate({ file, server }) {
      // If the plugin options file changes, invalidate virtual modules
      if (file.includes("vite.config")) {
        const ids = [RESOLVED_TRPC, RESOLVED_SUPABASE, RESOLVED_ROUTER];
        const modules = ids
          .map((id) => server.moduleGraph.getModuleById(id))
          .filter((m): m is NonNullable<typeof m> => m != null);
        server.ws.send({ type: "full-reload" });
        return [...modules];
      }
    },
  };
}

// ─── Named export alias for convenience ──────────────────────────────────────
export default fullstackPlugin;

// ─── Type augmentation for virtual modules ────────────────────────────────────
// Consumers should add this to their tsconfig `paths` or `types`:
//
//   "virtual:trpc":    ["./plugins/vite-plugin-fullstack"],
//   "virtual:supabase":["./plugins/vite-plugin-fullstack"],
//   "virtual:router":  ["./plugins/vite-plugin-fullstack"],
