/**
 * n8n Pipeline Callback Handler
 *
 * When the n8n workflow completes, it POSTs results to /api/pipeline/n8n-callback.
 * This handler validates the secret, processes the results, and updates the letter status.
 */

import type { Express, Request, Response } from "express";
import {
  createLetterVersion,
  updateLetterStatus,
  updateLetterVersionPointers,
  logReviewAction,
  getLetterRequestById,
} from "./db";
import { runAssemblyStage } from "./pipeline";
import type { IntakeJson, ResearchPacket } from "../shared/types";
import { sendLetterReadyEmail } from "./email";
import { getUserById } from "./db";

interface N8nCallbackPayload {
  letterId: number;
  success: boolean;
  researchOutput?: string;
  draftContent?: string;
  error?: string;
}

export function registerN8nCallbackRoute(app: Express): void {
  app.post("/api/pipeline/n8n-callback", async (req: Request, res: Response) => {
    const callbackSecret = process.env.N8N_CALLBACK_SECRET ?? "";

    // Validate the callback secret
    const incomingSecret = req.headers["x-ttml-callback-secret"] as string;
    if (callbackSecret && incomingSecret !== callbackSecret) {
      console.warn("[n8n Callback] Invalid callback secret received");
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const payload = req.body as N8nCallbackPayload;
    const { letterId, success, researchOutput, draftContent, error } = payload;

    if (!letterId) {
      res.status(400).json({ error: "letterId is required" });
      return;
    }

    console.log(`[n8n Callback] Received for letter #${letterId}, success=${success}`);

    // Acknowledge immediately
    res.json({ received: true, letterId });

    // Process asynchronously
    try {
      if (!success || !draftContent) {
        const errMsg = error ?? "n8n pipeline returned no content";
        console.error(`[n8n Callback] Pipeline failed for letter #${letterId}: ${errMsg}`);
        await updateLetterStatus(letterId, "submitted"); // revert to allow retry
        await logReviewAction({
          letterRequestId: letterId,
          actorType: "system",
          action: "pipeline_failed",
          noteText: `n8n pipeline failed: ${errMsg}`,
          fromStatus: "researching",
          toStatus: "submitted",
        });
        return;
      }

      // Store the n8n draft as an AI draft version
      const draftVersion = await createLetterVersion({
        letterRequestId: letterId,
        versionType: "ai_draft",
        content: draftContent,
        createdByType: "system",
        metadataJson: {
          provider: "n8n",
          stage: "n8n-pipeline",
          researchOutput: researchOutput ? researchOutput.substring(0, 2000) : undefined,
        },
      });
      const draftVersionId = (draftVersion as any)?.insertId ?? 0;
      await updateLetterVersionPointers(letterId, { currentAiDraftVersionId: draftVersionId });

      // Now run Stage 3: Claude final assembly to polish the n8n output
      const letter = await getLetterRequestById(letterId);
      if (letter?.intakeJson) {
        try {
          const intake = letter.intakeJson as IntakeJson;

          // Build a minimal research packet from n8n's research output
          const research: ResearchPacket = {
            researchSummary: researchOutput ?? "Research completed by n8n Perplexity agent.",
            jurisdictionProfile: {
              country: intake.jurisdiction?.country ?? "US",
              stateProvince: intake.jurisdiction?.state ?? "",
              city: intake.jurisdiction?.city ?? "",
              authorityHierarchy: ["Federal", "State", "Local"],
            },
            issuesIdentified: [intake.matter?.description?.substring(0, 200) ?? "Legal matter"],
            applicableRules: [{
              ruleTitle: "n8n Research Findings",
              ruleType: "statute",
              jurisdiction: intake.jurisdiction?.state ?? "",
              citationText: "See research summary",
              sectionOrRule: "N/A",
              summary: (researchOutput ?? "").substring(0, 500),
              sourceUrl: "",
              sourceTitle: "n8n Perplexity Research",
              relevance: "Primary research from n8n pipeline",
              confidence: "medium" as const,
            }],
            localJurisdictionElements: [],
            factualDataNeeded: [],
            openQuestions: [],
            riskFlags: [],
            draftingConstraints: [],
          };

          const draftOutput = {
            draftLetter: draftContent,
            attorneyReviewSummary: "Draft generated by n8n pipeline (Perplexity + GPT-4o). Please review carefully.",
            openQuestions: [],
            riskFlags: [],
          };

          // Stage 3: Claude polishes the n8n draft
          await runAssemblyStage(letterId, intake, research, draftOutput);
          console.log(`[n8n Callback] Stage 3 Claude assembly complete for letter #${letterId}`);
        } catch (assemblyErr) {
          const assemblyMsg = assemblyErr instanceof Error ? assemblyErr.message : String(assemblyErr);
          console.warn(`[n8n Callback] Stage 3 assembly failed for letter #${letterId}: ${assemblyMsg}. Using n8n draft as final.`);

          // If Claude fails, use the n8n draft directly — still land at generated_locked so subscriber pays to unlock
          await updateLetterStatus(letterId, "generated_locked");
          await logReviewAction({
            letterRequestId: letterId,
            actorType: "system",
            action: "ai_pipeline_completed",
            noteText: `n8n pipeline complete (Perplexity + GPT-4o). Claude assembly skipped. Draft ready — awaiting subscriber payment for attorney review.`,
            fromStatus: "drafting",
            toStatus: "generated_locked",
          });
        }
      } else {
        // No intake found — still land at generated_locked so subscriber pays to unlock
        await updateLetterStatus(letterId, "generated_locked");
        await logReviewAction({
          letterRequestId: letterId,
          actorType: "system",
          action: "ai_pipeline_completed",
          noteText: `n8n pipeline complete. Draft ready — awaiting subscriber payment for attorney review.`,
          fromStatus: "drafting",
          toStatus: "generated_locked",
        });
      }

      // Send "letter ready" email to subscriber (non-blocking)
      try {
        const letterRecord = await getLetterRequestById(letterId);
        if (letterRecord) {
          const subscriber = await getUserById(letterRecord.userId);
          const appBaseUrl = process.env.VITE_APP_ID
            ? `https://${process.env.VITE_APP_ID}.manus.space`
            : "https://talk-to-my-lawyer.manus.space";
          if (subscriber?.email) {
            await sendLetterReadyEmail({
              to: subscriber.email,
              name: subscriber.name ?? "Subscriber",
              subject: letterRecord.subject,
              letterId,
              appUrl: appBaseUrl,
              letterType: letterRecord.letterType ?? undefined,
              jurisdictionState: letterRecord.jurisdictionState ?? undefined,
            });
            console.log(`[n8n Callback] Letter-ready email sent to ${subscriber.email} for letter #${letterId}`);
          }
        }
      } catch (emailErr) {
        console.error(`[n8n Callback] Failed to send letter-ready email for #${letterId}:`, emailErr);
      }

      console.log(`[n8n Callback] Processing complete for letter #${letterId}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[n8n Callback] Error processing callback for letter #${letterId}:`, msg);
    }
  });
}
